<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Password Assistance</title>
<style>
*{margin:0px;padding:0px;font-family: helvetica, sans-serif;}
</style>
</head>
<body style="background:#f6f6f6 url(http://videocrm.com/images/email/bg.jpg) repeat-x;">
<div style="height:auto;width:78%;margin:0px auto;padding:25px 10px 0px 10px;">
  <div style="height:100px;"> <img src="http://52.11.63.176/public/images/VideoCRM_Logo.png" alt="Video CRM"> </div>
  <div style="min-height:200px;height:auto;background:#fff;border-top:5px solid #fbba3a;">
    <h2 style="font-size: 32px;color: #555555;margin:30px 10% 30px 10%;">Password Assistance</h2>
    <p style="font-size:13px;color:#99A1A6;line-height:19px;margin:0px 10% 20px 10%;">	
We received a request to reset the password associated with this email address. If you made this request, please follow the instructions below.</p>
    <p style="font-size:13px;color:#99A1A6;line-height:19px;margin:0px 10% 20px 10%;">Click on the link below to reset your password using our secure server:<br />
<a href="{{details.url}}" style="padding: 8px;	background: #DA5454;	font-size: 13px;	color: #ffffff;	text-decoration: none;	font-weight: bold;	display: inline-block;">Click here!</a>
<!-- <a style="color:#1c88bc;text-decoration:none;" href="{{details.url}}">{{details.url}}</a> -->
</p>
    <p style="font-size:13px;color:#99A1A6;line-height:19px;margin:0px 10% 20px 10%;">If you did not request to have your password reset you can safely ignore this email. Rest assured your customer account is safe.<br />
If clicking the link does not seem to work, you can copy and paste the link into your browser's address window, or retype it there. Once you have returned to Video CRM, we will give instructions for resetting your password.</p><br />
    <p style="font-size:12px; border-top:1px solid #ddd;padding-top:15px;color:#99A1A6;line-height:19px;margin:0px 10% 20px 10%;">VideoCRM will never email you and ask you to disclose or verify your VideoCRM password, credit card, or banking account number. If you receive a suspicious email with a link to update your account information, do
not click on the linkͭinstead, report the email to VideoCRM for investigation. Greetings from VideoCRM</p>
    <br clear="all" />
  </div>
  <div style="height:30px;background:#1c88bc;line-height:30px;color:#fff;text-align:center;font-size:12px;"><span>Copyright ©2015 <a href="index.php" style="color:#fff;text-decoration:none;">Video CRM</a>. All Right Reserved.</span></div>
</div>
</body>
</html>
